// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BicycleParkingsController from "./bicycle_parkings_controller"
application.register("bicycle-parkings", BicycleParkingsController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import Popover from '@stimulus-components/popover'
application.register('popover', Popover)
