services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
      CAPYBARA_SERVER_HOST: rails
      CAPYBARA_APP_HOST: http://rails
      REDIS_URL: redis://redis:6379
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
  selenium_chrome:
    image: seleniarm/standalone-chromium:4.17.0
    ports:
      - "4444:4444"
volumes:
  db-data:
  redis-data:
  bundle: